import 'package:cloud_firestore/cloud_firestore.dart';

class HandymanApproval {
  // PROPERTIES
  final String? approvalId;
  final String status;
  final String handymanId;
  final String requestId;

  // CONSTRUCTORS
  HandymanApproval({
    this.approvalId,
    required this.status,
    required this.handymanId,
    required this.requestId,
  });

  factory HandymanApproval.fromFireStore(
    DocumentSnapshot<Map<String, dynamic>> snapshot,
    //SnapshotOptions? options,
  ) {
    final data = snapshot.data();
    return HandymanApproval(
      approvalId: snapshot.id,
      status: data?['status'],
      handymanId: data?['handymanId'],
      requestId: data?['requestId'],
    );
  }

  // METHODS
  Map<String, dynamic> toFirestore() {
    return {
      //approval id auto generated by fb
      'status': status,
      'handymanId': handymanId,
      'requestId': requestId,
    };
  }
}
