import 'package:cloud_firestore/cloud_firestore.dart';
import 'dart:io';

class Offer {
  // PROPERTIES
  final String? offerId;
  final double bidPrice;
  final String status;
  final String description;
  final String attachment;
  final String userId;
  final String requestId;

  // CONSTRUCTORS
  Offer({
    this.offerId,
    required this.bidPrice,
    required this.status,
    required this.description,
    required this.attachment,
    required this.userId,
    required this.requestId,
  });

  factory Offer.fromFireStore(
    DocumentSnapshot<Map<String, dynamic>> snapshot,
    //SnapshotOptions? options,
  ) {
    final data = snapshot.data();
    return Offer(
      offerId: snapshot.id,
      bidPrice: data?['bidPrice'],
      status: data?['status'],
      description: data?['description'],
      attachment: data?['attachment'],
      userId: data?['userId'],
      requestId: data?['requestId'],
    );
  }

  // METHODS
  Map<String, dynamic> toFirestore() {
    return {
      // offerId auto generated by fb
      'bidPrice': bidPrice,
      'status': status,
      'description': description,
      'attachment': attachment,
      'userId': userId,
      'requestId': requestId
    };
  }
}
