import 'package:cloud_firestore/cloud_firestore.dart';
import 'dart:io';
import 'package:intl/intl.dart';

final formatter = DateFormat.yMd();

class Report {
  // PROPERTIES
  final String? reportId;
  final String issue;
  final String proof;
  final String status;
  final DateTime? createdAt;
  final String userId;

  // CONSTRUCTORS
  Report(
      {this.reportId,
      required this.issue,
      required this.proof,
      required this.status,
      this.createdAt,
      required this.userId});

  factory Report.fromFireStore(
    DocumentSnapshot<Map<String, dynamic>> snapshot,
    //SnapshotOptions? options,
  ) {
    final data = snapshot.data();
    return Report(
      reportId: snapshot.id,
      issue: data?['issue'],
      proof: data?['proof'],
      status: data?['status'],
      createdAt: (data?['createdAt'] as Timestamp?)?.toDate() ?? DateTime.now(),
      userId: data?['userId'],
    );
  }

  // METHODS
  Map<String, dynamic> toMap() {
    return {
      // reportId auto generated by fb
      'issue': issue,
      'proof': proof,
      'status': status,
      'createdAt': createdAt ?? DateTime.now(),
      'userId': userId
    };
  }
}
