import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:intl/intl.dart';

final formatter = DateFormat.yMd();

class Request {
  // PROPERTIES
  final String? requestId;
  final String title;
  final String category;
  final String description;
  final String attachment; // file attachment
  final String address;
  final String date;
  final String time;
  final String progress;
  final String? instructions;
  final double suggestedPrice;
  final String? completionProof; // file attachment
  final DateTime? createdAt;
  final String userId;
  final String? handymanId;

  // CONSTRUCTORS
  Request(
      {this.requestId,
      required this.title,
      required this.category,
      required this.description,
      required this.attachment,
      required this.address,
      required this.date,
      required this.time,
      required this.progress,
      this.instructions,
      required this.suggestedPrice,
      this.completionProof,
      this.createdAt,
      required this.userId,
      this.handymanId});

  factory Request.fromFireStore(
    DocumentSnapshot<Map<String, dynamic>> snapshot,
    //SnapshotOptions? options,
  ) {
    final data = snapshot.data();
    return Request(
      requestId: snapshot.id,
      title: data?['title'],
      category: data?['category'],
      description: data?['description'],
      attachment: data?['attachment'],
      address: data?['address'],
      date: data?['date'],
      time: data?['time'],
      progress: data?['progress'],
      instructions: data?['instructions'],
      suggestedPrice: data?['suggestedPrice'],
      completionProof: data?['completionProof'],
      createdAt: (data?['createdAt'] as Timestamp?)?.toDate() ?? DateTime.now(),
      userId: data?['userId'],
      handymanId: data?['handymanId'],
    );
  }

  // METHODS
  Map<String, dynamic> toMap() {
    return {
      // requestId auto generated by fb
      'title': title,
      'category': category,
      'description': description,
      'attachment': attachment,
      'address': address,
      'date': date,
      'time': time,
      'progress': progress,
      'instructions': instructions,
      'suggestedPrice': suggestedPrice,
      'completionProof': completionProof,
      'createdAt': createdAt ?? DateTime.now(),
      'userId': userId,
      'handymanId': handymanId,
    };
  }
}
