import 'dart:io';
import 'package:cloud_firestore/cloud_firestore.dart';

enum Specialization {
  plumbing,
  carpentry,
  electrical,
  painting,
  maintenance,
  welding,
  housekeeping,
  roofing,
  installation,
  pestcontrol
}

class Request {
  // PROPERTIES
  final String? requestId;
  final String title;
  final Specialization category;
  final String description;
  final File attachment; // file attachment
  final String address;
  final DateTime dateTime;
  final String progress;
  final double suggestedPrice;
  final File? completionProof; // file attachment
  final DateTime? createdAt;
  final String userId;
  final String? handymanId;

  // CONSTRUCTORS
  Request(
      {this.requestId,
      required this.title,
      required this.category,
      required this.description,
      required this.attachment,
      required this.address,
      required this.dateTime,
      required this.progress,
      required this.suggestedPrice,
      this.completionProof,
      this.createdAt,
      required this.userId,
      this.handymanId});

  factory Request.fromFireStore(
    DocumentSnapshot<Map<String, dynamic>> snapshot,
    //SnapshotOptions? options,
  ) {
    final data = snapshot.data();
    return Request(
      requestId: snapshot.id,
      title: data?['title'],
      category: data?['category'],
      description: data?['description'],
      attachment: data?['attachment'],
      address: data?['address'],
      dateTime: data?['dateTime'],
      progress: data?['progress'],
      suggestedPrice: data?['suggestedPrice'],
      completionProof: data?['completionProof'],
      createdAt: data?['createdAt'],
      userId: data?['userId'],
      handymanId: data?['handymanId'],
    );
  }

  // METHODS
  Map<String, dynamic> toMap() {
    return {
      // requestId auto generated by fb
      'title': title,
      'category': category,
      'description': description,
      'attachment': attachment,
      'address': address,
      'dateTime': dateTime,
      'progress': progress,
      'suggestedPrice': suggestedPrice,
      'completionProof': completionProof,
      'createdAt': createdAt ?? DateTime.now(),
      'userId': userId,
      'handymanId': handymanId,
    };
  }
}
