import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:intl/intl.dart';

final formatter = DateFormat.yMd();

class Review {
  // PROPERTIES
  final String? reviewId;
  final double rating;
  final String comment;
  final DateTime? createdAt;
  final String userId;
  final String requestId;

  // CONSTRUCTORS
  Review({
    this.reviewId,
    required this.rating,
    required this.comment,
    this.createdAt,
    required this.userId,
    required this.requestId,
  });

  factory Review.fromFireStore(
    DocumentSnapshot<Map<String, dynamic>> snapshot,
    //SnapshotOptions? options,
  ) {
    final data = snapshot.data();
    return Review(
      reviewId: snapshot.id,
      rating: data?['rating'],
      comment: data?['comment'],
      createdAt: (data?['createdAt'] as Timestamp?)?.toDate() ?? DateTime.now(),
      userId: data?['userId'],
      requestId: data?['requestId'],
    );
  }

  // METHODS
  Map<String, dynamic> toMap() {
    return {
      // reviewId auto generated by fb
      'rating': rating,
      'comment': comment,
      'createdAt': createdAt ?? DateTime.now(),
      'userId': userId,
      'requestId': requestId,
    };
  }
}
