import 'package:cloud_firestore/cloud_firestore.dart';

class Transaction {
  // PROPERTIES
  final String? transactionId;
  final String amount;
  final String description;
  final String handymanId;
  final DateTime? createdAt;

  // CONSTRUCTORS
  Transaction({
    this.transactionId,
    required this.amount,
    required this.description,
    required this.handymanId,
    this.createdAt,
  });

  factory Transaction.fromFireStore(
    DocumentSnapshot<Map<String, dynamic>> snapshot,
    //SnapshotOptions? options,
  ) {
    final data = snapshot.data();
    return Transaction(
      transactionId: snapshot.id,
      amount: data?['amount'],
      description: data?['description'],
      handymanId: data?['handymanId'],
      createdAt: (data?['createdAt'] as Timestamp?)?.toDate() ?? DateTime.now(),
    );
  }

  // METHODS
  Map<String, dynamic> toFirestore() {
    return {
      // amountId auto generated by fb
      'amount': amount,
      'description': description,
      'handymanId': handymanId,
      'createdAt': createdAt ?? DateTime.now(),
    };
  }
}
